// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjtS38IGjsiLNNvKiDE-cNw7habDajgB8',
    appId: '1:1097241474840:android:5b513a53ab62248a49d06d',
    messagingSenderId: '1097241474840',
    projectId: 'school-472b3',
    databaseURL: 'https://school-472b3-default-rtdb.firebaseio.com',
    storageBucket: 'school-472b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUMx2npqgAh3m76-RkamgykBP1YNRkJyg',
    appId: '1:1097241474840:ios:521646ea7c02d9ff49d06d',
    messagingSenderId: '1097241474840',
    projectId: 'school-472b3',
    databaseURL: 'https://school-472b3-default-rtdb.firebaseio.com',
    storageBucket: 'school-472b3.appspot.com',
    androidClientId: '1097241474840-6csvjft5409s7ih4d4peolm62uae2tvv.apps.googleusercontent.com',
    iosClientId: '1097241474840-8089erk3erq7l94p27c6pe078vmmdue0.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminApp',
  );
}
